package dev.pschmitt.netboxandchill.qrsetup

import java.util.Base64
import kotlinx.serialization.json.Json

/** Pure encode/decode for setup QR payloads. It never logs or persists the token it handles. */
object QrConfigCodec {
    private const val URI_PREFIX = "netboxandchill://setup?p="
    private val json = Json { prettyPrint = false }

    class InvalidPayloadException : Exception("Not a valid NetBox and Chill setup code")

    class UnsupportedVersionException(val payloadVersion: Int) :
        Exception("This setup code was generated by a newer app version")

    fun looksLikeQrConfigUri(text: String): Boolean = text.trim().startsWith(URI_PREFIX)

    fun encodePayload(envelope: QrConfigEnvelope): String {
        require(envelope.baseUrl.isNotBlank() && envelope.token.isNotBlank())
        val bytes = json.encodeToString(QrConfigEnvelope.serializer(), envelope).toByteArray()
        return URI_PREFIX + Base64.getUrlEncoder().withoutPadding().encodeToString(bytes)
    }

    @Throws(InvalidPayloadException::class, UnsupportedVersionException::class)
    fun decodePayload(raw: String): QrConfigEnvelope {
        val encoded = raw.trim().removePrefix(URI_PREFIX)
        if (encoded == raw.trim()) throw InvalidPayloadException()
        val bytes =
            try {
                Base64.getUrlDecoder().decode(encoded)
            } catch (_: IllegalArgumentException) {
                throw InvalidPayloadException()
            }
        val envelope =
            try {
                json.decodeFromString(QrConfigEnvelope.serializer(), bytes.decodeToString())
            } catch (_: Exception) {
                throw InvalidPayloadException()
            }
        if (envelope.version > QrConfigEnvelope.CURRENT_VERSION) {
            throw UnsupportedVersionException(envelope.version)
        }
        if (envelope.baseUrl.isBlank() || envelope.token.isBlank()) {
            throw InvalidPayloadException()
        }
        return envelope
    }
}
